### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by tryashtar** [tryashtar/mapmaking-references#1]
- [ ] Documentation for blank tags
- [ ] Mob head icons
- [ ] Links to referenced tag formats (e.g. items or potion effects)
- [ ] Description of defaults, bounds, and when tags are changed by the game (also read-only tags)
